version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
    networks: 
      - scramble-game

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "DB_DATABASE=stickearn"
      - "DB_USERNAME=admin"
      - "DB_PASSWORD=admin"
    networks:
      - scramble-game
  
  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: stickearn
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - stickearn-db:/var/lib/mysql
    networks:
      - scramble-game
  cache:
    image: redis:3.0
    ports: 
      - "63791:6379"
networks:
  scramble-game:
    driver: "bridge"
volumes:
  stickearn-db: